PackageID:
Library:
  - Name:
    URL:
    Reference:
      - Author:
        URL:
Language:
  -
License:
  - Name:
    URL:
Repository:
  - Name:
    URL:
Version:
  - Name:
    URL:

Developer:
  - Tag:
    Name:
    URL:
Docs:
  - Name:
    URL:
Support:
  - Name:
    URL:
Framework:
  -
GPU: false
Trend:
  - Types:
      - Tag:
        Name:
    URL:
LengthScale:
  -
Correlation:
  - Types:
      - Tag:
        Name:
    URL:
Mixture: false
MixtureModels:
  - Types:
      - Tag:
        Name:
    URL:
